"""initial

Revision ID: eacd313d197d
Revises: 
Create Date: 2026-02-20 16:35:00.383369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacd313d197d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_dates',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('color_bg', sa.String(), nullable=False),
    sa.Column('color_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'calendar_date')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('selected_dates')
    # ### end Alembic commands ###
